version: '3'

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_DB=${POSTGRES_DB}'
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7.0.11-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
  migrate:
    image: migrate/migrate:v4.16.2
    profiles:
      - 'tools'
    volumes:
      - ./migrations:/migrations
    entrypoint:
      - 'migrate'
      - '-path'
      - '/migrations'
      - '-database'
      - '${DATABASE_URL}'
    command:
      - 'up'
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
volumes:
  db-data:
  redis:
