[tool.ruff]
line-length = 120
ignore = ["E741", "E203"]

[tool.ruff.lint]
extend-select = ["UP019", "I001"]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
docstring-code-format = true

[tool.ruff.lint.isort]
force-single-line = true
