line-length = 90

[lint]
extend-select = ["UP019", "I001"]
ignore = ["E741", "E203"]

[format]
quote-style = "single"
indent-style = "space"
docstring-code-format = true

[lint.isort]
force-single-line = true
